{"name": "test_last_user_order_displayed_correctly[firefox-locator1]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Текст '169126' не появился в элементе ('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')", "trace": "self = <tests.test_feed_page.TestFeedPage object at 0x106300160>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"c98b789e-859e-4845-a698-9e8bd6a8358e\")>\nlogged_in_user = {'email': 'u1lf7u95@test.com', 'name': 'kzhbgr', 'password': 'ox2h56m4q9'}\nlocator = ('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')\n\n    @allure.story(\"Проверка отображения последнего созданного заказа в ленте\")\n    @pytest.mark.parametrize(\n        \"locator\",\n        [\n            FeedPageLocators.LAST_ORDER_NUMBER,\n            FeedPageLocators.ORDER_IN_PROGRESS\n        ]\n    )\n    def test_last_user_order_displayed_correctly(self, driver, logged_in_user, locator):\n        feed_page = FeedPage(driver)\n        feed_page.open()\n    \n        order = OrderHelper.create_order_with_login(\n            logged_in_user['email'], logged_in_user['password'], Ingredients.DEFAULT_INGREDIENTS\n        )\n        created_order_number = str(order[\"order\"][\"number\"])\n    \n>       feed_page.wait_for_text_in_element(locator, created_order_number)\n\ntests/test_feed_page.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/base_page.py:77: in wait_for_text_in_element\n    WebDriverWait(self.driver, 5).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"c98b789e-859e-4845-a698-9e8bd6a8358e\")>\nmethod = <function text_to_be_present_in_element.<locals>._predicate at 0x106362ca0>\nmessage = 'Текст \\'169126\\' не появился в элементе (\\'xpath\\', \\'//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li\\')'\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Текст '169126' не появился в элементе ('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')\n\n../../../pycharm_project/qa_python4/.venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Открыть страницу ленты заказов", "status": "passed", "steps": [{"name": "Открыть страницу: 'https://stellarburgers.nomoreparties.site/feed'", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/feed'"}], "start": 1736701298360, "stop": 1736701298701}], "start": 1736701298360, "stop": 1736701298701}, {"name": "Ожидаю появления текста ''169126'' в элементе: ('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Текст '169126' не появился в элементе ('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')\n\n", "trace": "  File \"/Users/oxanaklimocheva/Documents/pycharm_project/qa_python4/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/oxanaklimocheva/Documents/yandex/diplom/diplom_UI/pages/base_page.py\", line 77, in wait_for_text_in_element\n    WebDriverWait(self.driver, 5).until(\n  File \"/Users/oxanaklimocheva/Documents/pycharm_project/qa_python4/.venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')"}, {"name": "expected_text", "value": "'169126'"}], "start": 1736701301461, "stop": 1736701306727}], "parameters": [{"name": "driver", "value": "'firefox'"}, {"name": "locator", "value": "('xpath', '//*[@id=\"root\"]/div/main/div/div/div/div[1]/ul[2]/li')"}], "start": 1736701298360, "stop": 1736701306739, "uuid": "36d5fae7-f8ee-4cc1-be3a-c78fe847b6c4", "historyId": "c0eda716a919952f4d15f7825a70b93c", "testCaseId": "029caeb1af365969f49d89c57e455083", "fullName": "tests.test_feed_page.TestFeedPage#test_last_user_order_displayed_correctly", "labels": [{"name": "epic", "value": "Тесты страницы ленты заказов"}, {"name": "story", "value": "Проверка отображения последнего созданного заказа в ленте"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed_page"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "Oxanas-MacBook-Pro.local"}, {"name": "thread", "value": "67012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed_page"}]}